language: python
python:
- 2.7

if: tag IS present

env:
  global:
  - COMMIT=${TRAVIS_COMMIT::8}
  - REPO=wangkexiong/intellij
  - IDEA_BUILD=2020.1
  - secure: i8qfloy5VMpSavmKJxKlb9Ky/ZjDeIgDuYJa2p0nXIDJOXyCC0yxmkYQtOOW5IaQYVLqVeEdxEEYCaBleHzZxPP/txfPDDEKN4sbiqDrGVi+cTirgxehXxGjpeKd66XS4nrF4Eq4O1ggGNG9gxSaZKrkSG9CNGZSE6rpBXIgiv7jZVt9P4KKAtU2oWOaAPydDZ5/WIGCCz/BEojgy5Jca/alV81/toFfgW3vtBMsgb6z1zQIgjw26/ym6GJNbYGV4W2QTY1NnBFYIcu07POc+RJIEjOUcIkD9hvwJElGrNyV4e+Er6NvxIdkqxqNIWzSBHs7WPUwzzl8UrnuRBkFsumaDLdtIVHHhuZFvWyvQsdi3ciE7Ztd75NzHUQZ+68TJYFlWZTO/WEqa/heFlFtyRzNZN6UAk3+neEGpq/wc8gMyjCANCWETG21Qq/dHEFuwCqm1EfO3hrMGm5MF+RR9hycwvFhRAlSG7mPWzrcPz+aL3oLNmEr/Y7A2YO06yKBgpI/VYk/afPh/TD/pxICcom5EbPaO1VwxEm4bmNxEkdm13Hmweyl92A1ucPXfx1lXLkzsyll3o12SqFHHqwmBtikGNI+b6oroU4GiXb1o6FuVylDqmdJEvlO4Kl+PqlKpfkCTK5PLS+BGkL/2Dxj15/GpQrAEH6tSAGmfqSA1Yk=
  - secure: d1+0YZO/CuRmGhU7Npt4Agiv4thXQDDBhN5cXyahLWVz7Gzeq43uOinYKSa7fNRZaiy/uD60QVmtWYBjyRuzfOewNzDKZQ/WDkZYpFFHFQZXq8lED6C4iNO0C/Q4VT5aqCMIcJkKC5bdq6T0U2S4S2fKhyeiAA6IX7N38h0H9Evdo+LnNvW0SozNgPEuWg4jToXJoP/O2NYoOIFjZxbFnAJnYQwI4LQfpZIP6OzQqEZBa6Uqg4MPM5vVGzytydUCgZW5DlaUXIYg7pyJiFk+Gi38esl3uuleELyGuz4MjV3HWM5McTzHLkrqll1xnL2QcxoCaW+geAIiz5+lQtp3XnzbV8eVYel7YqX2YJ3WNyp0wIAL3Pja0jnO9m8Pp59+ZZRlnsrYBqabQrhNfxqs52DrdUDt5LgXRzOrRPtPHNL1aUEyvAJ5VD3N4ozAX+ouls+Kozt+GIpknn96XOerPS32d4P9kn4GVbiV1RjyYs7cxiWEBbUy5m8YJyE4IM3FK0EHqIE9m048GxHmRDWeQVsS+SW40/8cSnlV5cspbCzMSDSVR2bZ4tF3m+Ycf0/Me79ZWtDgE3zDQJ+ZhIYd+Nz5x7/cBy2Qr9E43zAv8noVIbyRDEpvc7X3YU3lgYE58CN4nEkQY/yCHIzGET8I8WS7FMewC57PwRDuO0eh17c=

services:
- docker

install:
- docker build --build-arg IDEA_BUILD=${IDEA_BUILD} -t $REPO:$COMMIT .

script:
- docker run -t $REPO:$COMMIT java -version

after_success:
- docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
- docker tag $REPO:$COMMIT $REPO:$TRAVIS_TAG
- docker tag $REPO:$COMMIT $REPO:latest
- docker push $REPO:$TRAVIS_TAG
- docker push $REPO:latest
